package main

import (

    _ "github.com/mukmin-life/docs" // docs is generated by Swag CLI, you have to import it.

    swagger "github.com/swaggo/fiber-swagger"
	"github.com/gofiber/fiber/v2"
    "log"
)

func main() {
	app := fiber.New()

	app.Get("/docs/*", swagger.WrapHandler)
	v2 := app.Group("/v2")
	prayer_time := v2.Group("/prayer_time")

	prayer_time.Get("/", func(c *fiber.Ctx) error {
		c.JSON(fiber.Map{
			"message": "🐣 v1",
		})
		return c.Next()
	})


    log.Fatal(app.Listen(":3000"))
}
