package main

import (

    _ "github.com/mukmin-life/docs" // docs is generated by Swag CLI, you have to import it.
    prayer_api "github.com/mukmin-life/prayer_time"

    swagger "github.com/swaggo/fiber-swagger"
	"github.com/gofiber/fiber/v2"
    "log"
)

// @title Mukmin Life API
// @version 1.0

// @contact.name Mukmin Life API Support
// @contact.email hello@mukmin.life

// @license.name Proprietary

// @host localhost:3000
// @BasePath /v2
func main() {
	app := fiber.New()

	app.Get("/docs/*", swagger.WrapHandler)
	api := app.Group("/")
	v2 := api.Group("/v2")

	prayer_time := v2.Group("/prayer_time")
	prayer_time.Get("", prayer_api.GetPrayerTime)

    log.Fatal(app.Listen(":3000"))
}
