// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package prayer_time

import (
	"time"
)

type PrayerTime struct {
	Date    time.Time
	Zone    string
	Hijri   string
	Imsak   time.Time
	Fajr    time.Time
	Syuruk  time.Time
	Dhuhr   time.Time
	Asr     time.Time
	Maghrib time.Time
	Isha    time.Time
}

type SchemaMigration struct {
	Version string
}
