// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package prayer_time

import (
	"context"
	"time"
)

const getPrayerTime = `-- name: GetPrayerTime :one
SELECT date, zone, hijri, imsak, fajr, syuruk, dhuhr, asr, maghrib, isha FROM prayer_times
WHERE date = $1 AND zone = $2 LIMIT 1
`

type GetPrayerTimeParams struct {
	Date time.Time
	Zone string
}

func (q *Queries) GetPrayerTime(ctx context.Context, arg GetPrayerTimeParams) (PrayerTime, error) {
	row := q.db.QueryRowContext(ctx, getPrayerTime, arg.Date, arg.Zone)
	var i PrayerTime
	err := row.Scan(
		&i.Date,
		&i.Zone,
		&i.Hijri,
		&i.Imsak,
		&i.Fajr,
		&i.Syuruk,
		&i.Dhuhr,
		&i.Asr,
		&i.Maghrib,
		&i.Isha,
	)
	return i, err
}
