// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package prayer_time

import (
	"time"
)

type PrayerTime struct {
	Date    time.Time `db:"date" json:"date"`
	Zone    string    `db:"zone" json:"zone"`
	Imsak   time.Time `db:"imsak" json:"imsak"`
	Fajr    time.Time `db:"fajr" json:"fajr"`
	Syuruk  time.Time `db:"syuruk" json:"syuruk"`
	Dhuhr   time.Time `db:"dhuhr" json:"dhuhr"`
	Asr     time.Time `db:"asr" json:"asr"`
	Maghrib time.Time `db:"maghrib" json:"maghrib"`
	Isha    time.Time `db:"isha" json:"isha"`
}
