basePath: /v2
definitions:
  prayer_time.PrayerTimeOutput:
    properties:
      asr:
        type: string
      dhuhr:
        type: string
      fajr:
        type: string
      imsak:
        type: string
      isha:
        type: string
      maghrib:
        type: string
      syuruk:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: hello@mukmin.life
    name: Mukmin Life API Support
  license:
    name: Proprietary
  title: Mukmin Life API
  version: "1.0"
paths:
  /prayer_time/{date}:
    get:
      consumes:
      - application/json
      description: get prayer time by date
      parameters:
      - description: Date
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/prayer_time.PrayerTimeOutput'
      summary: List prayer times of the day
swagger: "2.0"
